apiVersion: app.appvia.io/v2beta1
kind: AppEnv
metadata:
  name: rbc-test-app-from-app2-template-dev
spec:
  name: dev
  stage: nonprod
  application: rbc-test-app-from-app2-template
  cloud: azure
  clusterRef:
    group: compute.appvia.io
    kind: Cluster
    name: aks-stdnt1
    namespace: ws-to1
    version: v2beta1