apiVersion: app.appvia.io/v2beta1
kind: AppComponent
metadata:
  name: rbc-test-app-from-app2-template-storage-account-app
spec:
  application: rbc-test-app-from-app2-template
  container:
    containers:
    - env:
      - fromCloudResourceOutput:
          componentName: rbc-test-app-from-app2-template-storage-account
          output: SECONDARY_ACCESS_KEY
        name: PRIMARY_ACCESS_KEY
      - fromCloudResourceOutput:
          componentName: rbc-test-app-from-app2-template-storage-account
          output: NAME
        name: AZURE_STORAGE_ACCOUNT_NAME
      - fromCloudResourceOutput:
          componentName: rbc-test-app-from-app2-template-storage-account
          output: CONTAINER_NAME
        name: AZURE_CONTAINER_NAME
      image: ghcr.io/digital-garage-icl/student-rbc-test-app-from-app2-template:latest
      name: ui
      ports:
      - containerPort: 3002
        name: ui
        protocol: TCP
      securityContext:
        runAsGroup: 999
        runAsUser: 999
    expose:
      container: ui
      port: 3002
    tls: true
  dependsOn:
  -  rbc-test-app-from-app2-template-storage-account
  name: rbc-test-app-from-app2-template-storage-account-app
  type: Container
